//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage_Details
    {
        public Nullable<bool> Staring { get; set; }
        public Nullable<bool> HOOD { get; set; }
        public Nullable<bool> Front_Bumper { get; set; }
        public Nullable<bool> Front_Passenger_side_fender { get; set; }
        public Nullable<bool> Passenger_door { get; set; }
        public Nullable<bool> Rear_assenger_side_quarter_panel { get; set; }
        public Nullable<bool> Rear_bumper { get; set; }
        public Nullable<bool> Rear_Trunk { get; set; }
        public Nullable<bool> Driver_door { get; set; }
        public Nullable<bool> Undercarriage { get; set; }
        public int Policy_Number { get; set; }
    }
}
