//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication46.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Involed_Party
    {
        public int Id { get; set; }
        public string Frist_Name { get; set; }
        public string Last_Name { get; set; }
        public string Insurance_Provider { get; set; }
        public Nullable<int> Year { get; set; }
        public string Model { get; set; }
        public Nullable<int> Policy_Number { get; set; }
        public string Phone_Number { get; set; }
    }
}
